### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by callicles** [gitlinks/gitrank-web#1]
For the repository view
https://precursorapp.com/document/GitRank-repository-view-17592200279569

**Comment by sheymann** [comment]
Warning: displaying the current score before asking to make a review will influence the reviewer. It's a known psychological issue.

**Comment by callicles** [comment]
ok, what would you propose as an alternative ?

**Comment by sheymann** [comment]
What is the context and purpose of the current wireframes? How the user will access them?

**Comment by callicles** [comment]
It is supposed to be the page representing a repo/project. You land on it when you click on a badge. Its purpose is to give more details on the score and suggest rating for people who did no rate the project. 
I am not sure asking for a score right away is the best policy though, what we want is make it easy for people to see scores first, then enable them to rate repos easily.

**Comment by callicles** [comment]
Should we try to also display last question asked on the subject on stackoverflow ?
