### ISSUE TITLE
Créer une instance docker avec les données de GHTorrent

### ISSUE THREAD

**Issue by pocman** [gitlinks/gitrank-web#10]
https://registry.hub.docker.com/_/mysql/

**Comment by pocman** [comment]
this seems to do the trick : http://depressiverobot.com/2015/02/19/mysql-dump-docker.html
docker run --name dump -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -d mysql
wget http://ghtorrent.org/downloads/pull_requests-dump.2015-03-29.tar.gz
tar -xvzf pull_requests-dump.2015-03-29.tar.gz
docker exec -i dump mysql -uroot -proot < dump/github/pull_requests.bson

**Comment by pocman** [comment]
@jacobtardieu Il faudrait aussi créer un user full rights et ouvrir le port de la machine au monde.

**Comment by jacobtardieu** [comment]
Ok, je suis en train d'importer les données, ça prend vraiment beaucoup beaucoup de temps mais c'est noté, je dis quand c'est bon.

**Comment by pocman** [comment]
Il est possible que même le plus petit dump soit déjà trop important pour
notre machine... Tu as vu que j'avais mis le tar dans /Data ?
