### ISSUE TITLE
Design the model of the graph database

### ISSUE THREAD

**Issue by callicles** [gitlinks/gitrank-web#13]

**Comment by callicles** [comment]
http://grokbase.com/t/gg/neo4j/135w1kw5xr/storing-document-text-in-node-property-text-analysis-possible

Pour nous neo4j devrait suffire pour stocker les feedback

**Comment by callicles** [comment]
@pocman What kind of granularity do we need for storing scores and Karma?

**User Karma:** We should save all history of Karma modifications
**Repo Score:** We should store all detailed scoring of all users. And all change history of the meta score.

When a user votes again for a repo, it overrides its former score.

same a big texts I have concern about storing all the history in Neo. I would be much more comfortable with a SQL db for this.

**Comment by callicles** [comment]
@jacobtardieu http://www.thedotpost.com/2015/06/paul-dix-time-series-data-the-worst-and-best-use-case-in-distributed-databases

**Comment by callicles** [comment]
Here is what I think the neo4j model should look like.

![Neo4j Model](https://docs.google.com/drawings/d/1rwcvb2adpUhAopaPPc2P3KJ6-3NBPEttNSc0vwCOH88/pub?w=1145&h=732)

As mentioned before, I also think we should keep all history of scores and karma into a SQL database such as PostgresSQL (neo won't handle time series properly)

**Comment by pocman** [comment]
Il manque le Karma dans les properties du score.
Il manque karma_weight du score courant

**Comment by callicles** [comment]
No Postgresql for the moment.
