### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by callicles** [gitlinks/gitrank-web#35]
Implement real search for the form in the navbar

**Comment by brunnoattorre** [comment]
Right now, the API for Full-text search on neo4j 2.0 onward is deprecated (http://neo4j.com/docs/stable/indexing-introduction.html). So, if we decide to use this API, we will have to change it down the road. Our options are:
1- Use the legacy API and change it afterwards.
2- Don't use the legacy API and use a regex text search on the repos while the full text search is not integrated on neo4j 2.0. This is not ideal but it's better than what we have right now and we wouldn't have to waste a lot of time on the search part.
3-  Use a combination of Elasticsearch and Neo4j. This is time consuming but it seems as a nice permanent solution
