### ISSUE TITLE
prevent people from voting again once they have voted once

### ISSUE THREAD

**Issue by callicles** [gitlinks/gitrank-web#39]
People should only be able to vote once so that they can't influence too much on the scores. 

Later we should have score update reminders. For example I vote now on a repo, I should be able to update my vote 2 months later. As a consequence, If I have changed my mind on something in the mean time, I can get it right.

**Comment by brunnoattorre** [comment]
Instead of not allowing voting twice, the score is updated.

**Comment by pocman** [comment]
This doesn't work for me.
The RepositoryService.canUpdateFeedback seems to return the opposite of what it's suppose to.
