### ISSUE TITLE
Make Play Production ready

### ISSUE THREAD

**Issue by callicles** [gitlinks/gitrank-web#42]
Look at the play configuration for the production environment

https://www.playframework.com/documentation/2.4.x/Production

**Comment by pocman** [comment]
Modify circle.yml, add 
notify:
  webhooks:
    # A list of hook hashes, containing the url field
    - url: https://example.com/hooks/circle
Modify Flash app, to parse circle payload
Create script : 
git checkout vcs_revision
activator clean stage
cd stage/universal/
kill Running_pid
bin/root "-Dconfig.file=conf/application.staging.conf"

**Comment by pocman** [comment]
For production, continuous deployment on (only) one instance is not really recommended.
We should just ssh our way to the new release version.

If you really want continuous deployment, we can talk about elastic beanstalk...
