### ISSUE TITLE
Actor model Repo/User

### ISSUE THREAD

**Issue by pocman** [gitlinks/gitrank-web#5]
Actor system should model propagation of ratings.

**Comment by pocman** [comment]
I just created a branch for this issue. 
I added actors and a service, we should speak about that tomorrow, I'm not used to play and it's workflow
https://github.com/gitlinks/gitrank-web/tree/feature/5_actor_model

**Comment by pocman** [comment]
@callicles I need an implementation for  
UserDao =>
def findAll: Future[Seq[User]]

**Comment by callicles** [comment]
This should be paginated, right ?

**Comment by pocman** [comment]
A stream?
