### ISSUE TITLE
Refactor the Json stream parsing 

### ISSUE THREAD

**Issue by brunnoattorre** [gitlinks/gitrank-web#52]
Currently, the parsing of the neo4j response is being made in a stream-like manner. This is done with the help of a Jackson Library, which is more syntactically "Java".
We should refactor this to a more scala-like way, perhaps using some akka features

**Comment by callicles** [comment]
By reading the meeting report from last week, we have also to take a look at how the stream is handled. From Thomas remark there is a possibility to overload the pool of requests with the streaming of users.
