### ISSUE TITLE
Prevent people from voting for the repositories they contribute to

### ISSUE THREAD

**Issue by callicles** [gitlinks/gitrank-web#56]
A user should not be able to give feedback to a repository he contributes to

**Comment by pocman** [comment]
This happens too late when adding feedback to our own repo.
After adding pocman/gp2, 
I was redirected to No registered feedback for this repository, yet
And I was able to click on Add First Feedback...

**Comment by pocman** [comment]
contribution taking into account are 90 days old or less.
