### ISSUE TITLE
Bug on creating repos

### ISSUE THREAD

**Issue by brunnoattorre** [gitlinks/gitrank-web#64]
When the user that sign-up is the owner of the repo, the repo is being created without the owner on it's name.

**Comment by callicles** [comment]
I just tested that and that works fine on my branch

**Comment by pocman** [comment]
I was able to reproduce the bug.
404 is only returned the first time.
<img width="1489" alt="capture d ecran 2015-09-28 a 21 27 11" src="https://cloud.githubusercontent.com/assets/1695808/10146199/c8e92c7a-6627-11e5-8d4b-19a3b06da643.png">

**Comment by pocman** [comment]
This does not seems to apply to "forked only" projects.

**Comment by pocman** [comment]
I was not able to reproduce on localhost...
