### ISSUE TITLE
Previous and Next buttons on repo page should be deactivated

### ISSUE THREAD

**Issue by jacobtardieu** [gitlinks/gitrank-web#72]
Seen on http://dev.gitrank.io/github/apache/spark?page=1, the previous and next buttons are always active even if there is only one page. It crashes when we click on it (Exception for previous and no feedback for next).
More generally we should protect the input of the query parameter  `page`.

**Comment by pocman** [comment]
The current code doesn't look good.

**Comment by callicles** [comment]
Will do that

**Comment by jacobtardieu** [comment]
Still happening : http://dev.gitrank.io/github/elastic/elasticsearch?page=1 (previous and next buttons below feedbacks).
