### ISSUE TITLE
404 when adding a project

### ISSUE THREAD

**Issue by pocman** [gitlinks/gitrank-web#79]
Most of the time I have a 404 when adding a project.
Second call is working.

**Comment by pocman** [comment]
@callicles Don' you have this issue ?

**Comment by callicles** [comment]
No :(

**Comment by callicles** [comment]
Looks like Brunno also have it. We should explore that.

**Comment by pocman** [comment]
When adding some feedback, I'm redirected to "no feedback yet" the first time.
I'm guessing, redirection is too fast.

**Comment by callicles** [comment]
Yes, the switch to the SPA client should fix that

**Comment by brunnoattorre** [comment]
This issue is related to a limit on the number of calls made to Github. The fix for this is to add the github_client id and secret to the calls made to github, increasing the number of calls from 60 to 5000 per hour.
https://developer.github.com/v3/#rate-limiting
