### ISSUE TITLE
Home page should list popular repos

### ISSUE THREAD

**Issue by pocman** [gitlinks/gitrank-web#91]
#### When log out, the home page should list popular (stared) repos by language.
The page should be a simplyfied github search page.
<img width="1040" alt="gitrank home page" src="https://cloud.githubusercontent.com/assets/1695808/10413240/f5062b22-6fa1-11e5-8d9f-27c1213c5812.png">

#### When log in, the home page should list repos stared by the current user.
Like the [your stars page](https://github.com/stars?direction=desc&filter=others&sort=stars)
<img width="1018" alt="gitrank login home page" src="https://cloud.githubusercontent.com/assets/1695808/10413257/bbed5dbe-6fa2-11e5-81d6-e1ba16cfba67.png">

#### We should probably use the [Github Java Api which support 100% of the GitHub v3 API](https://github.com/eclipse/egit-github/tree/master/org.eclipse.egit.github.core)
`libraryDependencies += "org.eclipse.mylyn.github" % "org.eclipse.egit.github.core" % "2.1.5"`

**Comment by jacobtardieu** [comment]
We should put some more elements on the front page:
- Short text explaining what gitrank is
- Big search box with autocomplete
- Example repos (Thats what this issue was about)

I've made a draft on google drawing to express my ideas: https://docs.google.com/drawings/d/1TH738InAsokXLGhuSBksSPX27faAPdNVAwmpwJ37mvE/edit

Don't hesitate to comment or to modify!

**Comment by callicles** [comment]
I made some mocks, which one do you prefer ?

![screen shot 2015-11-01 at 1 15 22 pm](https://cloud.githubusercontent.com/assets/4429209/10870497/c6d27292-809a-11e5-9d22-f0ac8ac0a955.png)
![screen shot 2015-11-01 at 12 43 09 pm](https://cloud.githubusercontent.com/assets/4429209/10870496/c6d03e28-809a-11e5-98dd-4412510ebc8e.png)
![screen shot 2015-11-01 at 12 53 05 pm](https://cloud.githubusercontent.com/assets/4429209/10870499/c6d3a4be-809a-11e5-9311-31f4374cce4d.png)
![screen shot 2015-11-01 at 12 54 22 pm](https://cloud.githubusercontent.com/assets/4429209/10870498/c6d3676a-809a-11e5-9ba5-996acafff053.png)

**Comment by brunnoattorre** [comment]
I prefer the first one

**Comment by callicles** [comment]
You can also combine some attributes if you think that's better

**Comment by jacobtardieu** [comment]
First one, could we add the gitrank score if available?

**Comment by jacobtardieu** [comment]
But I think we should put the full description of gitrank in the first as in the other ones.

**Comment by callicles** [comment]
Hum, I can see some pros and cons in adding the score.

Pros:
- Gives an overview on what gitrank is about

Cons:
- Influences the user in the rating when going on the first time
- Does not push the user to actually go on the repo page, which we would like to happen

**Comment by jacobtardieu** [comment]
Good points, but I think the main issue now is that it is hard to understand what gitrank is about without someone explaining.
